task5
Kulich0/esoft-task_5 pull request #1
Opened 2024-05-08 18:50 UTC by Kulich0

2024-05-23 18:38 UTC, Unaccommodating reviewed
Мне нравится твоя работа!) Зачтено

2024-05-28 20:44 UTC, Kulich0 commented
> Мне нравится твоя работа!) Зачтено

может все-таки есть какие-то замечания?

2024-05-31 19:14 UTC, Unaccommodating requested changes
по структуре и логике нареканий нет

2024-05-31 19:14 UTC, Unaccommodating commented on src/components/UI/CommentForm/CommentForm.jsx
> +const CommentForm = ({onCommentSubmit}) => {
отступы между импортами и компонентой, плохо читается

2024-05-31 19:14 UTC, Unaccommodating commented on src/Pages/DetailPage.jsx
> +            console.log('Новый комментарий:', newCommentData);
не забывай убирать после разработки

2024-06-11 16:18 UTC, merged